# Generated by Django 5.0.1 on 2025-03-16 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('pnr', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('train_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.trainroute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
