# Generated by Django 5.0.1 on 2025-03-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
